FROM ruby:3.1.2 AS builder

ENV RAILS_ENV=development

RUN gem uninstall bundler
RUN gem install bundler -v 2.3.24 --no-document

WORKDIR /app
COPY Gemfile Gemfile.lock /app/

RUN bundle install

# Copy the application codes
COPY . /app/
