version: '3'
services:
  db:
    image: mysql:8.0
    # for mac M1
    # platform: linux/amd64
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - '43306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - './docker/db/conf.d:/etc/mysql/conf.d'

  redis:
    image: redis:6.0
    ports:
      - "26379:6379"

  web:
    image: gcp-rails-demo-web:latest
    # Add platform for mac M1
    #platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh ./docker-entrypoint.dev.sh
    environment:
      PORT: 8080
    volumes:
      - ".:/app"
      - $GOOGLE_APPLICATION_CREDENTIALS:/root/sa_adc.json
    ports:
      - "18080:8080"
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true

  gcloudtasks:
    image: ghcr.io/aertje/cloud-tasks-emulator:latest
    command: -host 0.0.0.0 -port 8123 -queue "projects/zigexn-vn-sandbox/locations/asia-northeast1/queues/zigexn-vn-sandbox-default"
    ports:
      - "8123:8123"
    environment:
      APP_ENGINE_EMULATOR_HOST: http://web:8080

volumes:
  mysql-data:
